### ISSUE TITLE
机器异常重启之后mydan.bootstrap.master 没自动起来 删除var/lock/bootstrap/lock 之后可以恢复

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#12]
问题, 机器异常重启后 mydan的agent 没起来.

查了下 是lock的pid (var/lock/bootstrap/lock) 还存在,不过机器重启后 被其他的进程占用PID了.

我猜测是下面这个代码有点问题.

个人建议 MYDan::Util::ProcLock 的check函数加上 cat /proc/$pid/cmdline 查看下 是不是 mydan.bootstrap.master  加一层确认. 现在貌似只判断pid是否存在与否.

MYDan::Bootstrap

    our ( $logs, $exec, $lock ) = @$this{qw( logs exec lock )};
    my $proclock = MYDan::Util::ProcLock->new( "$lock/lock" );

    if ( my $pid = $proclock->check() )
    {
        print "master locked by $pid.\n" if $ENV{MYDan_DEBUG};
        exit;
    }

    $proclock->lock();
    $0 = 'mydan.bootstrap.master';

**Comment by lijinfeng2011** [comment]
已改成使用文件锁方式:   
 my $flock = MYDan::Util::FLock->new( "$lock/lock" );
 die "Locked by other processes.\n" unless $flock->lock();
