### ISSUE TITLE
go/mssh bug

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#13]
I use go/mssh to esxi or some linux which shell is zsh  will HANG

you can reappear like  this
chsh to /bin/zsh

FIX
using 
 [ qr/[#\$%\]]\s*/ => sub { $exp->interact; } ],  ## the esxi  default like [root@wdhtest1:~]  so add \]

IN 
   $exp->expect
    (
        $TIMEOUT,
        [ qr/yes\/no/ => sub { $exp->send( "yes\n" ); exp_continue; } ],
        [ qr/[#\$%\]]\s*/ => sub { $exp->interact; } ],
        [ qr/$prompt$/ => sub { $exp->send( $pass ); $exp->interact; } ],
        map{ my $v = $expect{$_};[ qr/$_/ => sub { $exp->send( "$v\n" ); exp_continue; } ] }keys %expect
    );

我猜现在Util/GO.pm 和 Util/ExpSSH.pm 有部分重合的地方, 你应该会打算和并下.

**Comment by lijinfeng2011** [comment]
提示符没能和代码中的正则匹配上的，可以通过配置的方式进行匹配。
linux的提示符是可以修改的，如果该提示符不是普遍的情况，请修改提示符或者改配置文件。
