### ISSUE TITLE
Util/ExpSSH.pm 依赖 nc

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#14]
Util/ExpSSH.pm  有proxy的时候 依赖NC  ( -o ProxyCommand='nc -X 5 -x $x{$node{$node}} %h %p' )
我从最小的系统安装MYDan的时候, 没nc 执行的时候报错.希望可以在安装的时候可以装上依赖.

NC的各个操作系统的版本感觉功能都不太一样,  tools/shell 也依赖 NC, (my $scan = `nc -z localhost 65111-65333`;)

你觉得是否有必要 写一个perl 版本的呢?

**Comment by g112wdh** [comment]
MYDan::Util::Gateway 依赖lsof

**Comment by lijinfeng2011** [comment]
依赖的nc和lsof等工具，在安装的时候安装这些工具依赖比较麻烦。而且各种系统的包管理工具都有差异，很有可能包管理工具（如yum）都没有。没有打算去做安装时候这些工具的依赖安装。 如果你有精力可以修改一下
