### ISSUE TITLE
tools/mcmd 输出问题

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#15]
之前版本的
 mcmd -r '10.95.22.{1~254}' 'fping {}'

---
status:
  10.95.22.{2~13,15~20,24,31~34,37~254}: 1  10.95.22.{1,14,21~23,25~30,35~36}: 0
---
stdout:
  10.95.22.{2~13,15~20,24,31~34,37~254}: {} is unreachable
  10.95.22.{1,14,21~23,25~30,35~36}: {} is alive

现在用了 MYDan::VSSH::Print::result( 'mcmd' => %re ); 
好像丢失了 返回结果汇总的功能了

其实很多事情 mcmd 是用来做高并发的 bash for循环使用的, 输入的一般都是主机名或者ip的range
希望执行完成之后 依旧能汇总.
OPS 最常见的使用方式 是
1. mcmd -r range 'fping {}'
2. mcmd -r range 'nc -zv {} 22'
3. 在deploy/janus 里面的check. 如果是一个集群几百台机器, 返回回来汇总成range 会非常好用.

希望恢复这个之前的输出.

**Comment by lijinfeng2011** [comment]
输出结果中操作对象换乘{} 这个部分的代码我删了，如果你经常要用这个我可以做个选项。默认开这个功能我怕回引起使用的人的误解，如果他cat一个文件，里面刚好有这个机器的ip，会变成｛｝， 这样比较奇怪

**Comment by g112wdh** [comment]
这个还是需要的.

**Comment by lijinfeng2011** [comment]
已经在0.1.19版本中修改，mcmd 加--xx参数时，输出的结果会把机器ip进行替换成{}
