### ISSUE TITLE
MYDan/Agent/Proxy.pm 在 mydan/etc/agent/proxy 为空文件时候(全部注释)

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#16]
mydan/etc/agent/proxy  全注释了, 之后 导致如vssh 不能用
error: not HASH at /home/work/mydan/perl/lib/site_perl/5.24.0/MYDan/Agent/Proxy.pm line 38

confess "error: not HASH" if ref $conf ne 'HASH';  

全部注释了之后$conf 好像是undef 的
个人建议在这个前面加一句
$conf = {} if ! defined $conf;

你看下怎么弄会更好? 比如mydan/etc/agent/proxy   上做一些限制等?

**Comment by lijinfeng2011** [comment]
已经在0.1.19版本中修复
