### ISSUE TITLE
关于mydan/etc/alias

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#17]
这个默认还是需要长期的维护
今天设置PATH=/home/work/mydan/dan/tools:/usr/local/sbin:/usr/local/bin

到在rsync 卡住了,
在mydan/etc/alias 增加
rsync: /usr/bin/rsync

这种tools/rsync  和系统重名字的一定要加alias 不然就死循环了
这个issues 一直开着 后面谁看到了往里添加

**Comment by lijinfeng2011** [comment]
不是，这个的问题是，你不应该把tools下面的路径放到PATH中，你要放就放 mydan/bin , 里面的命令会包含所有的工具
