### ISSUE TITLE
grsync/load 问题

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#21]
当文件的owner 有问题的时候 ( 如文件是从其他机器拷贝过来的时候, 文件的uid 对应用户不存在)
如
-rwxrwxrwx. 1 15720 15720     1527 12月 16 00:15 ntpsync

这个时候 grsync的时候 会出如下的问题.

@400000005a475f0100000000 [agent] [STDOUT] Missing argument in printf at /opt/mydan/dan/agent/code/load line 19, <> ch
unk 1.                                        

导致拷贝失败.

期望修正.
1. 这个是一直在拷贝,拷贝完毕之后md5对应不上, retry 3次, 最后失败, 应该修正成  先报错. 
我测试的时候文件比较大,拷贝了T*3 之后 才报错.
2. grsync 应该和scp rsync 一样, 在没有指定 chown 的情况下 应该 保持文件的原有属性.

    printf "%d:%s:%s:%s:",
        $size, Digest::MD5->new()->addfile( $fh )->hexdigest(),( getpwuid($uid) )[0], $mode;
应该是 getpwuid($uid) 这个有问题. 

我把 文件chown 成root 拷贝成功

**Comment by lijinfeng2011** [comment]
1.
uid 不存在，不会导致错误，导致错误的可能情况是拷贝的源文件对应的用户id没有对应的用户名。
这时候如果需要保持文件owner信息是办不到的，这时就会拷贝失败。
因为文件的owner本来就有问题，所以没办法保持文件owner。

2.

I.拷贝过程可能会有异常情况，异常发生后，会根据重试参数控制重试，拷贝是分多步完成的，有些情况下是从中间状态开始的，重试的时候是有可能成功的。如果不想重试就可用通过参数来控制

II. grsync 和mrsync默认情况下不保持稳健的属性。可用通过--cc参数来指定继承，也可用通过chown和chmod指定。 在grsync使用的时候，会有三个类型的机器，源机器、目标机器、控制机器。在多隔离网络中同步数据，会通过控制机器来保持临时文件，这个情况下如果使用了--cc 参数来保持文件属性，很可能会失败，控制机上很可能不会有对应的用户，可用通过chown和chmod来指定，这个时候临时文件不需要保持文件原来的属性
