### ISSUE TITLE
rename error

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#22]
mydan/dan/agent/code/dump 

这个插件的
下面语句
&$unlink( $temp, 'rename fail' ) unless rename $temp, $path;

当/tmp 和 文件的目标(-path 指定) 不是一个文件系统的时候 会报错.  如果打印 $!  报错信息是 Invalid cross-device

perldoc -f rename 里面说
For example, it will usually not work across file
            system boundaries,

测试了下  改成这样就可以 跑通了.
&$unlink( $temp, 'rename fail' ) if ( system( "mv $temp $path" ) != 0 );

**Comment by lijinfeng2011** [comment]
mayi项目中的所有rename已经更换成system mv
