### ISSUE TITLE
mydan node purge 功能

### ISSUE THREAD

**Issue by g112wdh** [MYDan/mayi#23]
mydan node purge -?
SYNOPSIS
    Delete node databases entries

     $0 --cluster clusters --table table [--key nodes] [--value values]
与下面的不符合
$option->assert(qw( cluster table key value ));

个人建议 只留cluster 可以让我们直接一个cluster 删除 

执行完毕后 可以执行下cache

**Comment by lijinfeng2011** [comment]
与什么不符？

**Comment by g112wdh** [comment]
[--key nodes] [--value values]  这个[] 是可选的, 下面的assert 表示强制. 我必须要 把  cluster table key value 
都输入 才可以删除, 意味着我不能 cluster 和 按table 全部删除.

**Comment by lijinfeng2011** [comment]
在0.1.33版本中已修复
