### ISSUE TITLE
能讲一下repo名字MYDan的由来么？

### ISSUE THREAD

**Issue by mysbupt** [MYDan/mayi#4]
看着好像My Dan。。。

**Comment by g112wdh** [comment]
@mysbupt 你给想个深层次的含义呗， 好让我写到简历里面

**Comment by lijinfeng2011** [comment]
MYDan😄

**Comment by mysbupt** [comment]
@g112wdh 你好歹也贡献几行代码:smile:，这样才能秀简历啊

**Comment by lijinfeng2011** [comment]
欢迎来 mydan频道讨论 https://webchat.freenode.net/?channels=#mydan
